import 'package:flutter/material.dart';

class L10n {
  final String code;
  final String name;
  final TextDirection direction;

  const L10n({
    required this.code,
    required this.name,
    required this.direction,
  });

  static const List<L10n> supported = [
    L10n(code: 'ar', name: 'العربية', direction: TextDirection.rtl),
    L10n(code: 'en', name: 'English', direction: TextDirection.ltr),
  ];
}

class Localization {
  static const Map<String, Map<String, String>> _dict = {
    'ar': {
      'welcome_title': 'دعوة زفاف متميزة',
      'welcome_subtitle': 'بكل الحب، يسعدنا دعوتكم',
      'open_invitation': 'افتح الدعوة',
      'invite_title': 'دعوة زفاف',
      'invite_subtitle': 'يسعدنا دعوتكم لمشاركتنا فرحتنا',
      'invite_desc': 'بكل حب وسعادة، ندعوكم لحضور حفل زفافنا، ونتشرف بتواجدكم معنا في هذه اللحظة الغالية على قلوبنا.',
      'story_title': 'قصتنا',
      'story_desc': 'بدأت قصتنا بلقاء بسيط تحول إلى حب حقيقي، وها نحن اليوم نبدأ فصلاً جديداً من حياتنا معاً، بإذن الله.',
      'countdown_title': 'العد التنازلي',
      'countdown_days': 'يوم',
      'countdown_hours': 'ساعة',
      'countdown_minutes': 'دقيقة',
      'countdown_seconds': 'ثانية',
      'countdown_finished': 'حان الوقت السعيد! 🌸',
      'location_title': 'مكان الحفل',
      'btn_directions': 'احصل على الاتجاهات',
      'schedule_title': 'برنامج الحفل',
      'rsvp_title': 'يسعدنا تأكيد حضوركم',
      'rsvp_desc': 'نرجو تأكيد الحضور من خلال ملء النموذج التالي لتسهيل الترتيبات.',
      'rsvp_name': 'الاسم الكامل',
      'rsvp_name_error': 'يرجى إدخال اسمك الكريم',
      'rsvp_attendance': 'هل ستشرفنا بالحضور؟',
      'rsvp_yes': 'نعم، بكل سرور! 🎉',
      'rsvp_no': 'للأسف، لا أستطيع الحضور 😔',
      'rsvp_guests': 'عدد المرافقين',
      'rsvp_message': 'رسالة تهنئة للعروسين',
      'rsvp_submit': 'تأكيد الحضور',
      'rsvp_submitting': 'جاري الإرسال...',
      'rsvp_success_title': 'تم تأكيد الحضور بنجاح!',
      'rsvp_success_desc': 'شكراً جزيلاً لك، نتطلع لرؤيتك ومشاركتنا هذه الفرحة الغالية.',
      'rsvp_success_no': 'شكراً لك، نتمنى لو كنت معنا، ونسعد بمباركتك عن بعد.',
      'rsvp_error': 'حدث خطأ ما، يرجى المحاولة مرة أخرى.',
      'rsvp_new_submission': 'تأكيد جديد',
      'gift_title': 'هدية العروسين',
      'gift_desc': 'حضوركم ومشاركتكم فرحتنا هي أغلى هدية في العالم بالنسبة لنا. لمن يرغب بتقديم هدية مادية، يسعدنا تواصلكم.',
      'thank_you_title': 'شكراً لكم',
      'thank_you_desc': 'وجودكم يزيدنا فرحاً وسعادة، شكراً لمشاركتكم أجمل لحظات حياتنا.',
      'footer_text': 'صُممت هذه الدعوة بكل حب © 2026',
      'admin_title': 'لوحة تحكم الدعوة',
      'admin_desc': 'قم بتخصيص كافة تفاصيل الدعوة وعرض الحضور بشكل فوري.',
      'admin_save': 'حفظ التعديلات',
      'admin_saving': 'جاري حفظ التعديلات...',
      'admin_success_save': 'تم حفظ التعديلات بنجاح!',
      'admin_bride': 'اسم العروس',
      'admin_groom': 'اسم العريس',
      'admin_wedding_date': 'تاريخ الزفاف',
      'admin_wedding_time': 'وقت الزفاف',
      'admin_wedding_day': 'يوم الأسبوع',
      'admin_venue_name': 'اسم القاعة',
      'admin_venue_address': 'عنوان القاعة',
      'admin_target_date': 'تاريخ العد التنازلي (ISO)',
      'admin_story_text': 'نص قصة الحب',
      'admin_music_track': 'رابط أو مسار الموسيقى',
      'admin_rsvp_list': 'قائمة الحضور المؤكدين',
      'admin_no_rsvps': 'لا يوجد تأكيدات حضور بعد.',
      'admin_rsvp_guest_format': 'الاسم: {name} | الحضور: {att} | المرافقين: {guests}',
      'admin_colors_fonts': 'الألوان والخطوط',
      'admin_primary_color': 'اللون الأساسي (Hex)',
      'admin_secondary_color': 'اللون الثانوي (Hex)',
      'admin_accent_color': 'اللون المساعد (Hex)',
      'admin_font_heading': 'خط العناوين',
      'admin_font_body': 'خط النصوص',
      'admin_btn_close': 'إغلاق',
      'admin_btn_open': 'لوحة التحكم',
      'admin_section_toggles': 'تفعيل/تعطيل الأقسام',
      'admin_music_slider': 'مستوى الصوت الافتراضي',
      'admin_show_story': 'قسم القصة',
      'admin_show_countdown': 'قسم العد التنازلي',
      'admin_show_gallery': 'قسم الألبوم',
      'admin_show_location': 'قسم الموقع',
      'admin_show_schedule': 'برنامج الحفل',
      'admin_show_gift': 'قسم الهدايا',
      'admin_show_rsvp': 'قسم تأكيد الحضور',
      'nav_story': 'قصتنا',
      'nav_countdown': 'العد التنازلي',
      'nav_gallery': 'الألبوم',
      'nav_location': 'المكان',
      'nav_schedule': 'البرنامج',
      'nav_gift': 'الهدايا',
      'nav_rsvp': 'تأكيد الحضور',
      'nav_admin': 'التحكم',
    },
    'en': {
      'welcome_title': 'Premium Wedding Invitation',
      'welcome_subtitle': 'With love, we invite you',
      'open_invitation': 'Open Invitation',
      'invite_title': 'Wedding Invitation',
      'invite_subtitle': 'We are delighted to share our joy',
      'invite_desc': 'With deep love and happiness, we invite you to attend our wedding celebration, and we would be honored by your presence on this most cherished day.',
      'story_title': 'Our Story',
      'story_desc': 'Our story began with a simple spark that bloomed into true love. Today, we begin a beautiful new chapter together under God\'s grace.',
      'countdown_title': 'The Countdown',
      'countdown_days': 'Days',
      'countdown_hours': 'Hours',
      'countdown_minutes': 'Mins',
      'countdown_seconds': 'Secs',
      'countdown_finished': 'The Happy Time Has Come! 🌸',
      'location_title': 'The Venue',
      'btn_directions': 'Get Directions',
      'schedule_title': 'The Schedule',
      'rsvp_title': 'We\'d Love to See You There',
      'rsvp_desc': 'Please confirm your attendance by completing the form below to help us with arrangements.',
      'rsvp_name': 'Full Name',
      'rsvp_name_error': 'Please enter your full name',
      'rsvp_attendance': 'Will you attend?',
      'rsvp_yes': 'Yes, with pleasure! 🎉',
      'rsvp_no': 'Regretfully, I cannot attend 😔',
      'rsvp_guests': 'Number of Companions',
      'rsvp_message': 'Wishes / Congratulatory Note',
      'rsvp_submit': 'Confirm Attendance',
      'rsvp_submitting': 'Confirming...',
      'rsvp_success_title': 'Attendance Confirmed!',
      'rsvp_success_desc': 'Thank you so much! We look forward to celebrating this glorious day with you.',
      'rsvp_success_no': 'Thank you. We wish you could be there, and we appreciate your remote blessings.',
      'rsvp_error': 'Something went wrong, please try again.',
      'rsvp_new_submission': 'New RSVP',
      'gift_title': 'Wedding Gifts',
      'gift_desc': 'Your presence and blessing is the greatest gift in the world to us. If you wish to contribute with a material gift, please contact us.',
      'thank_you_title': 'Thank You',
      'thank_you_desc': 'Your presence fills our hearts with joy. Thank you for sharing the most beautiful moment of our lives.',
      'footer_text': 'Designed with love © 2026',
      'admin_title': 'Invitation Control Dashboard',
      'admin_desc': 'Customize all aspects of the invitation and view real-time RSVPs instantly.',
      'admin_save': 'Save Changes',
      'admin_saving': 'Saving Changes...',
      'admin_success_save': 'Changes saved successfully!',
      'admin_bride': 'Bride\'s Name',
      'admin_groom': 'Groom\'s Name',
      'admin_wedding_date': 'Wedding Date',
      'admin_wedding_time': 'Wedding Time',
      'admin_wedding_day': 'Day of the Week',
      'admin_venue_name': 'Venue Name',
      'admin_venue_address': 'Venue Address',
      'admin_target_date': 'Countdown Date (ISO)',
      'admin_story_text': 'Love Story Content',
      'admin_music_track': 'Music Asset / Link',
      'admin_rsvp_list': 'Confirmed Guest List',
      'admin_no_rsvps': 'No RSVP submissions yet.',
      'admin_rsvp_guest_format': 'Name: {name} | Attending: {att} | Guests: {guests}',
      'admin_colors_fonts': 'Colors & Fonts',
      'admin_primary_color': 'Primary Color (Hex)',
      'admin_secondary_color': 'Secondary Color (Hex)',
      'admin_accent_color': 'Accent Color (Hex)',
      'admin_font_heading': 'Heading Font',
      'admin_font_body': 'Body Font',
      'admin_btn_close': 'Close',
      'admin_btn_open': 'Dashboard',
      'admin_section_toggles': 'Enable/Disable Sections',
      'admin_music_slider': 'Default Volume',
      'admin_show_story': 'Story Section',
      'admin_show_countdown': 'Countdown Section',
      'admin_show_gallery': 'Gallery Section',
      'admin_show_location': 'Location Section',
      'admin_show_schedule': 'Schedule Section',
      'admin_show_gift': 'Gift Section',
      'admin_show_rsvp': 'RSVP Section',
      'nav_story': 'Story',
      'nav_countdown': 'Countdown',
      'nav_gallery': 'Gallery',
      'nav_location': 'Venue',
      'nav_schedule': 'Schedule',
      'nav_gift': 'Gifts',
      'nav_rsvp': 'RSVP',
      'nav_admin': 'Admin',
    }
  };

  static String get(String langCode, String key) {
    return _dict[langCode]?[key] ?? key;
  }
}
